# Generated by Django 4.0.1 on 2022-01-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('bedroom', 'Bedroom'), ('drawing', 'Drawing Room'), ('living', 'Living Room'), ('kitchen', 'Kitchen'), ('garage', 'Garage'), ('basement', 'Basement')], max_length=40, null=True)),
                ('image', models.ImageField(upload_to='web/Gallery/')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ('id',),
            },
        ),
    ]
