# Generated by Django 4.0.1 on 2022-01-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twobhk',
            options={'ordering': ('id',), 'verbose_name': '2BHK Villa Detail', 'verbose_name_plural': '2BHK Villa Details'},
        ),
        migrations.RemoveField(
            model_name='twobhk',
            name='ground_floor_list_item',
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_floor_list_item', models.CharField(max_length=120)),
                ('twobhk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twobhk', to='web.twobhk')),
            ],
        ),
    ]
