# Generated by Django 4.0.1 on 2022-01-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_twobhk_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('bedroom', 'Bedroom'), ('drawing', 'Drawing Room'), ('living', 'Living Room'), ('kitchen', 'Kitchen'), ('garage', 'Garage'), ('basement', 'Basement')], max_length=40, null=True)),
                ('image', models.ImageField(upload_to='web/Gallery/')),
            ],
        ),
    ]
