# Generated by Django 4.0.1 on 2022-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('id',), 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
        migrations.DeleteModel(
            name='TwoBhk',
        ),
    ]
